### ISSUE TITLE
Pterodactyl server setup in .toml file, but bot does not run

### ISSUE THREAD

**Issue by Kickbut101** [fasko-web/discord-gameserver-bots#16]
I'm... fairly certain I have all the configs right (see below). But when I go to run "npm start" I get this as output:

        PS C:\Discord Bot for Pterodactyl\discord-gameserver-bots-2.0.2> npm start
        
        > discord-gameserver-bots@2.0.0 start C:\Discord Bot for Pterodactyl\discord-gameserver-bots-2.0.2
        > node ./bot.js

And that's it, nothing else.

I have node.js v14.17.3 installed. I ran the commands as instructed on the installation portion for dependencies and whatnot.

Windows 2016 is OS, though I imagine that probably doesn't matter.

.toml file

        # Gameserver Settings
        # Clone this .toml file, renaming it with your server's abbreviation
        [server]
        enabled = false
        name = "PterodactylBot" # Discord bot will set this as their username, and nickname whenever the username has changed
        # (Discord limits username changes to four an hour)
        game = 'garrysmod' # Defaults to garrysmod
        # see the full list at: https://github.com/gamedig/node-gamedig#games-list
        ip = '00.00.000.000'
        port = 27015 # Set to false or remove if not needed
        
        # Extra optional settings for game servers with weird queries
        query_port = false # Set if the game's server requires querying a specific port, expects an integer
        max_players = false # Set if the game's server query has trouble detecting max players, expects an integer
        
        # Discord Bot Settings
        [server.bot]
        token = 'my discord bots key/token' # Discord bot token for this game server
        color = '#00ADFF' # Used for embed colors
        
        [server.bot.status]
        type = 'PLAYING' # 'PLAYING' || 'WATCHING' || 'LISTENING' || 'STREAMING' || 'COMPETING'
        players = true # If true, shows current & max players in bot status
        map = true # If true, shows map in bot status
        
        # Pterodactyl Settings
        #   Provides a more accurate status, only use if your gameserver is hosted on a Pterodactyl panel
        #   Otherwise you can remove entirely
        [server.pterodactyl]
        enabled = true
        version = 'new' # If running Pterodactyl panel v1.0+ set to 'new', otherwise leave as 'old'
        url = '192.168.1.184' # Root location of your Pterodactyl panel, no trailing slash
        server_id = '1337' # ID of your server within the Pterodactyl panel
        api_key = 'api key from the user I made in pterodactyl panel'
        
        # Optional Settings
        [server.optional]
        connect_url = '' # Must be HTTP or HTTPS! steam:// unsupported by Discord
        rules_url = '' # Link to your server's rules, set to false if not needed
        content_url = '' # Link to a download of your server's content, set to false if not needed
        discords = [ # If the game server has seperate Discords, put them here
        { name = '', invite_code = '' },
        { name = '', invite_code = '' }
        ]

.env file

        COMMUNITY_NAME =
        
        COMMAND_BOT_PREFIX = server
        COMMAND_BOT_TOKEN = my discord bots key/token
        COMMAND_GUILD_IDS = myguildnumber/channelnumberfromdiscord
        SHOW_USER_INPUT = false
        
        SERVER_QUERY_INTERVAL = 1 minute
        WEB_QUERY_INTERVAL = 30 seconds
        PTERODACTYL_QUERY_INTERVAL = 15 seconds

**Comment by fasko-web** [comment]
Apologies for the delayed response. 

This repo should be archived (sorry about that), as the project can now be found [here](https://github.com/definitive-networks/discord-gameserver-bots).
It's in need of a rewrite, but it should address your problems, granted `/server connect` is currently busted.

**Comment by Kickbut101** [comment]
@fasko-web I am running discord-gameserver-bots-2.0.2.zip version for the record. So by turning the top property to enabled I should be able to get this running?

I'm pretty sure I opened this issue on the wrong page, I'm 99% sure I followed and used the release from the one you linked above

**Comment by fasko-web** [comment]
> So by turning the top property to enabled I should be able to get this running?

Yeah, as long as one server is enabled, the bots will start up.
